sudo: required
services: 
  - docker

before_install:
  - docker build -t sbalasubramanian14/portfolio -f Dockerfile.dev .

script:
  - docker run -e CI=true  sbalasubramanian14/portfolio npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "portfolio"
  env: "Portfolio-env"
  bucket_name: "elasticbeanstalk-us-east-2-101897022946"
  bucket_path: "portfolio"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"