sudo: required
services: 
  - docker

before_install:
  - docker build -t sbalasubramanian14/portfolio -f Dockerfile.dev .

script:
  - docker run -e CI=true  sbalasubramanian14/portfolio npm run test